mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtps
    username: xxx.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true